"""core canonical objects, protocols, value kinds, versions, exceptions.

see docs/architecture.md §4 (canonical vocabulary), §9 (canonical objects),
and §16 (project layout).

this module re-exports the core canonical names so downstream modules can
import from `extractx.core` without reaching into each submodule. the
tier-1 end-user surface (`extractx.__init__`) is deliberately separate.
"""

from __future__ import annotations

from .anchors import (
    AnchorMap,
    BoundingRegion,
    PageRef,
    SourceRef,
    SourceSpan,
    TextAnchorSpace,
    anchor_invert,
    anchor_lookup,
    anchor_validate_total,
    check_normalized_text_span,
    is_utf8_aligned,
    slice_utf8_byte_span,
    utf8_byte_span_to_char_range,
)
from .cardinality import Cardinality
from .contracts import (
    LLM,
    NLP,
    AcceptanceLifecycle,
    BatchSelector,
    Budget,
    BudgetDecision,
    CandidateFilter,
    CandidateSorter,
    CandidateStrategy,
    ClassificationContextStrategy,
    DocumentAdapter,
    Fetch,
    FieldValidator,
    GroundedProposalGenerator,
    InstancePlanner,
    InstanceProposer,
    InstanceResolver,
    InstanceValidator,
    Normalizer,
    Prompt,
    ProposalValidator,
    Reporter,
    SelectionAdapter,
    Selector,
)
from .dependencies import (
    DependencyEdges,
    topological_order,
    validate_dependency_graph,
)
from .exceptions import (
    CapabilityError,
    ExtractionFailed,
    InfrastructureError,
    InterviewError,
    SpecError,
)
from .filters import (
    And,
    ContainedBy,
    Contains,
    ContextContains,
    FilterExpr,
    LabelIn,
    LabelNotIn,
    Not,
    NumericRange,
    Or,
)
from .objects import (
    BudgetSpec,
    Candidate,
    CandidateOverflowMetadata,
    CandidateSet,
    ClassificationContextBinding,
    ClassificationContextOverflowMetadata,
    ClassificationContextSet,
    ClassificationContextWindow,
    ConstraintValue,
    ContextBudget,
    ContextPack,
    DistanceMetric,
    DocumentView,
    ExpectedConstraint,
    ExtractionSpec,
    FieldId,
    FieldSpec,
    FilterBinding,
    GroupingBinding,
    GroupingDiscriminator,
    GroupingEvidence,
    GroupingPolicy,
    InstanceCandidate,
    InstanceCandidateSet,
    InstanceGroupingKey,
    InstanceHint,
    InstancePlan,
    InstanceProposerBinding,
    InstanceProposerResponse,
    InstanceState,
    InterviewTranscript,
    Message,
    Observation,
    PredicateConstraint,
    PromptBinding,
    PromptPolicy,
    ProviderResult,
    RangeConstraint,
    RenderedPrompt,
    SchemaRef,
    SelectorBinding,
    SetConstraint,
    SorterBinding,
    StrategyBinding,
    StructuralFailure,
    StructuralStatus,
    UsageEvent,
    ValidationBinding,
    ValidationPolicy,
    ValidationReason,
)
from .outcomes import (
    ArtifactRef,
    Evidence,
    ExecutionTrace,
    Extraction,
    FieldRef,
    Instance,
    NegativeOutcome,
    ObjectIssue,
    ProposalProvenance,
    ProposedField,
    ValidatedField,
    ValidationFailure,
)
from .value_kinds import ValueKind
from .versions import (
    algorithmic_producer_version,
    soft_producer_version,
    stable_hash,
)

__all__ = [
    # anchors
    "AnchorMap",
    "BoundingRegion",
    "PageRef",
    "SourceRef",
    "SourceSpan",
    "TextAnchorSpace",
    "anchor_invert",
    "anchor_lookup",
    "anchor_validate_total",
    "check_normalized_text_span",
    "is_utf8_aligned",
    "slice_utf8_byte_span",
    "utf8_byte_span_to_char_range",
    # cardinality / value kinds
    "Cardinality",
    "ValueKind",
    # exceptions
    "CapabilityError",
    "ExtractionFailed",
    "InfrastructureError",
    "InterviewError",
    "SpecError",
    # canonical objects
    "BudgetSpec",
    "Candidate",
    "CandidateOverflowMetadata",
    "CandidateSet",
    "ClassificationContextBinding",
    "ClassificationContextOverflowMetadata",
    "ClassificationContextSet",
    "ClassificationContextWindow",
    "ConstraintValue",
    "ContextBudget",
    "ContextPack",
    "DistanceMetric",
    "DocumentView",
    "ExpectedConstraint",
    "ExtractionSpec",
    "FilterBinding",
    "FilterExpr",
    "FieldId",
    "FieldSpec",
    "GroupingBinding",
    "GroupingDiscriminator",
    "GroupingEvidence",
    "GroupingPolicy",
    "InstanceCandidate",
    "InstanceCandidateSet",
    "InstanceHint",
    "InstanceGroupingKey",
    "InstancePlan",
    "InstanceProposerBinding",
    "InstanceProposerResponse",
    "InstanceState",
    "InterviewTranscript",
    "LabelIn",
    "LabelNotIn",
    "Message",
    "Not",
    "PromptBinding",
    "PromptPolicy",
    "Observation",
    "PredicateConstraint",
    "RangeConstraint",
    "RenderedPrompt",
    "ProviderResult",
    "SchemaRef",
    "SelectorBinding",
    "SetConstraint",
    "SorterBinding",
    "StructuralFailure",
    "StructuralStatus",
    "StrategyBinding",
    "UsageEvent",
    "ValidationBinding",
    "ValidationPolicy",
    "ValidationReason",
    "And",
    "ContainedBy",
    "Contains",
    "ContextContains",
    "NumericRange",
    "Or",
    # outcomes
    "ArtifactRef",
    "Evidence",
    "Extraction",
    "FieldRef",
    "ExecutionTrace",
    "Instance",
    "NegativeOutcome",
    "ObjectIssue",
    "ProposalProvenance",
    "ProposedField",
    "ValidatedField",
    "ValidationFailure",
    # protocols
    "AcceptanceLifecycle",
    "Budget",
    "BudgetDecision",
    "BatchSelector",
    "CandidateFilter",
    "CandidateSorter",
    "CandidateStrategy",
    "ClassificationContextStrategy",
    "DocumentAdapter",
    "Fetch",
    "FieldValidator",
    "GroundedProposalGenerator",
    "InstanceResolver",
    "InstancePlanner",
    "InstanceProposer",
    "InstanceValidator",
    "LLM",
    "NLP",
    "Normalizer",
    "Prompt",
    "ProposalValidator",
    "Reporter",
    "SelectionAdapter",
    "Selector",
    # helpers
    "DependencyEdges",
    "algorithmic_producer_version",
    "soft_producer_version",
    "stable_hash",
    "topological_order",
    "validate_dependency_graph",
]
